[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/api/auth-signup"
  to = "/.netlify/functions/auth-signup"
  status = 200

[[redirects]]
  from = "/api/auth-login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth-logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/pages/*"
  to = "/.netlify/functions/pages"
  status = 200

[[redirects]]
  from = "/api/pages"
  to = "/.netlify/functions/pages"
  status = 200

[[redirects]]
  from = "/api/public/*"
  to = "/.netlify/functions/public"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200